// Auto-generated
let project = new Project('Juego');

project.addSources('Sources');
project.addLibrary("/Applications/ArmorySDK/armory");
project.addLibrary("/Applications/ArmorySDK/iron");
project.addLibrary("/Applications/ArmorySDK/lib/haxebullet");
project.addAssets("/Applications/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("/Applications/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('arm.node.MoverMira');
project.addParameter("--macro keep('arm.node.MoverMira')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('arm.node.MovimientosLadosyAtr_s');
project.addParameter("--macro keep('arm.node.MovimientosLadosyAtr_s')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('arm.node.MyCanvas');
project.addParameter("--macro keep('arm.node.MyCanvas')");
project.addParameter('arm.node.Lanzamiento');
project.addParameter("--macro keep('arm.node.Lanzamiento')");
project.addShaders("build_Juego_Entrega/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_Juego_Entrega/compiled/Assets/**", { notinlist: true });
project.addAssets("build_Juego_Entrega/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("/Applications/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/Applications/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("/Applications/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("Bundled/canvas/MyCanvas.files", { notinlist: true });
project.addAssets("Bundled/canvas/MyCanvas.json", { notinlist: true });
project.addAssets("Bundled/canvas/Temporizador.files", { notinlist: true });
project.addAssets("Bundled/canvas/Temporizador.json", { notinlist: true });
project.addAssets("Bundled/canvas/_themes.json", { notinlist: true });
project.addAssets("Captura de pantalla 2020-05-26 a las 18.21.36.png", { notinlist: true });
project.addAssets("Tronco.jpg", { notinlist: true });
project.addAssets("bosque-arboles-696x444.jpg", { notinlist: true });
project.addAssets("grama-1024x682.jpg", { notinlist: true });
project.addAssets("un-material-de-mimbre-tejido-amarillo-15920488.jpg", { notinlist: true });
project.addLibrary("/Applications/ArmorySDK/lib/zui");
project.addAssets("/Applications/ArmorySDK/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_resizable');


resolve(project);
